/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d592590a-d821-40d5-8fe5-3c3563f3cbe7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Uy4bUFJL2",
    "aws_user_pools_web_client_id": "2p401t1a1s5dlp1h3cbn5o0mu4",
    "oauth": {}
};


export default awsmobile;
